export const productsData =
[
    { id: 1, image: '../Images/Shoes1.png', title: "Jordan Air Jordan 1 Retro High OG Black White" , price: "$199.99" },
    { id: 2, image: '../Images/Shoes2.png', title: "Jordan W Air Jordan 1 Retro High OG Dusted Clay" , price: "$150.55" },
    { id: 3, image: '../Images/Shoes3.png', title: "Jordan Air Jordan 1 Low 85 Metallic Blue" , price: "$99.99" },
    { id: 4, image: '../Images/Shoes4.png', title: "Jordan W Air Jordan 1 Retro High OG White Metallic Gold" , price: "$19.99" },
    { id: 5, image: '../Images/Shoes5.png', title: "Jordan Air Jordan 1 Mid White Black" , price: "$200.44" },
    { id: 6, image: '../Images/Shoes6.png', title: "Jordan Air Jordan 1 Low Yellow Ochre" , price: "$300.12" },
    { id: 7, image: '../Images/Shoes7.png', title: "Jordan Air Jordan 1 Low Yellow Ochre" , price: "$199.99" },
    { id: 8, image: '../Images/Shoes8.png', title: "Jordan Air Jordan 1 Retro High OG Yellow" , price: "$150.55" },
    { id: 9, image: '../Images/Shoes9.png', title: "Nike W Air Max 1 87 Crepe Light Bone" , price: "$99.99" },
    { id: 10, image: '../Images/Shoes10.png', title: "Nike W Air Max Plus Reflective Platinum" , price: "$19.99" },
    { id: 11, image: '../Images/Shoes11.png', title: "Nike W Air Max Flyknit Venture Black Velvet Brown" , price: "$200.44" },
    { id: 12, image: '../Images/Shoes12.png', title: "Nike W Air Max 1 87 QS Multi Color" , price: "$300.12" },
    { id: 13, image: '../Images/Shoes13.png', title: "Nike W Air Max 1 LX Light Obsidian" , price: "$199.99" },
    { id: 14, image: '../Images/Shoes14.png', title: "Nike Air Max 97 OG Metallic Gold" , price: "$150.55" },
    { id: 15, image: '../Images/Shoes15.png', title: "Jordan W Air Jordan 1 Low Blue Whisper" , price: "$99.99" },
    { id: 16, image: '../Images/Shoes16.png', title: "Nike W Air Max 1 LX Rugged Orange" , price: "$19.99" },
    { id: 17, image: '../Images/Shoes17.png', title: "Converse Chuck 70 High Gingerbread Patch" , price: "$200.44" },
    { id: 18, image: '../Images/Shoes18.png', title: "Converse Chuck 70 High Triple Black" , price: "$300.12" },
    { id: 19, image: '../Images/Shoes19.png', title: "Converse Chuck 70 Marquis High Vintage White" , price: "$200.44" },
    { id: 20, image: '../Images/Shoes20.png', title: "Converse Chuck 70 High Patchwork Tawny Owl" , price: "$300.12" },
];